      module QRUpdate_Library

      implicit none

      contains

# include "qrupdate-1.1.2/src/cch1dn.f"
# include "qrupdate-1.1.2/src/cchdex.f"
# include "qrupdate-1.1.2/src/cchinx.f"
# include "qrupdate-1.1.2/src/cchshx.f"
# include "qrupdate-1.1.2/src/cgqvec.f"
# include "qrupdate-1.1.2/src/clu1up.f"
# include "qrupdate-1.1.2/src/clup1up.f"
# include "qrupdate-1.1.2/src/cqrdec.f"
# include "qrupdate-1.1.2/src/cqrder.f"
# include "qrupdate-1.1.2/src/cqrinc.f"
# include "qrupdate-1.1.2/src/cqrinr.f"
# include "qrupdate-1.1.2/src/cqrshc.f"
# include "qrupdate-1.1.2/src/dch1dn.f"
# include "qrupdate-1.1.2/src/dch1up.f"
# include "qrupdate-1.1.2/src/dchdex.f"
# include "qrupdate-1.1.2/src/dchinx.f"
# include "qrupdate-1.1.2/src/dchshx.f"
# include "qrupdate-1.1.2/src/dgqvec.f"
# include "qrupdate-1.1.2/src/dlu1up.f"
# include "qrupdate-1.1.2/src/dlup1up.f"
# include "qrupdate-1.1.2/src/dqr1up.f"
# include "qrupdate-1.1.2/src/dqrdec.f"
# include "qrupdate-1.1.2/src/dqrder.f"
# include "qrupdate-1.1.2/src/dqrinc.f"
# include "qrupdate-1.1.2/src/dqrinr.f"
# include "qrupdate-1.1.2/src/dqrshc.f"
# include "qrupdate-1.1.2/src/sch1dn.f"
# include "qrupdate-1.1.2/src/sch1up.f"
# include "qrupdate-1.1.2/src/schdex.f"
# include "qrupdate-1.1.2/src/schinx.f"
# include "qrupdate-1.1.2/src/schshx.f"
# include "qrupdate-1.1.2/src/sgqvec.f"
# include "qrupdate-1.1.2/src/slu1up.f"
# include "qrupdate-1.1.2/src/slup1up.f"
# include "qrupdate-1.1.2/src/sqr1up.f"
# include "qrupdate-1.1.2/src/sqrdec.f"
# include "qrupdate-1.1.2/src/sqrder.f"
# include "qrupdate-1.1.2/src/sqrinc.f"
# include "qrupdate-1.1.2/src/sqrinr.f"
# include "qrupdate-1.1.2/src/sqrshc.f"
# include "qrupdate-1.1.2/src/zch1dn.f"
# include "qrupdate-1.1.2/src/zchdex.f"
# include "qrupdate-1.1.2/src/zchinx.f"
# include "qrupdate-1.1.2/src/zchshx.f"
# include "qrupdate-1.1.2/src/zgqvec.f"
# include "qrupdate-1.1.2/src/zlu1up.f"
# include "qrupdate-1.1.2/src/zlup1up.f"
# include "qrupdate-1.1.2/src/zqrdec.f"
# include "qrupdate-1.1.2/src/zqrder.f"
# include "qrupdate-1.1.2/src/zqrinc.f"
# include "qrupdate-1.1.2/src/zqrinr.f"
# include "qrupdate-1.1.2/src/zqrshc.f"

      end module

# include "qrupdate-1.1.2/src/zqhqr.f"
# include "qrupdate-1.1.2/src/zqrtv1.f"
# include "qrupdate-1.1.2/src/zqrqh.f"
# include "qrupdate-1.1.2/src/zqrot.f"
# include "qrupdate-1.1.2/src/zqr1up.f"
# include "qrupdate-1.1.2/src/zaxcpy.f"
# include "qrupdate-1.1.2/src/dqhqr.f"
# include "qrupdate-1.1.2/src/dqrqh.f"
# include "qrupdate-1.1.2/src/dqrtv1.f"
# include "qrupdate-1.1.2/src/dqrot.f"
# include "qrupdate-1.1.2/src/cqhqr.f"
# include "qrupdate-1.1.2/src/cqrtv1.f"
# include "qrupdate-1.1.2/src/cqrot.f"
# include "qrupdate-1.1.2/src/cqrqh.f"
# include "qrupdate-1.1.2/src/cqr1up.f"
# include "qrupdate-1.1.2/src/caxcpy.f"
# include "qrupdate-1.1.2/src/cch1up.f"
# include "qrupdate-1.1.2/src/sqrtv1.f"
# include "qrupdate-1.1.2/src/sqrot.f"
# include "qrupdate-1.1.2/src/sqhqr.f"
# include "qrupdate-1.1.2/src/sqrqh.f"
# include "qrupdate-1.1.2/src/zch1up.f"

