#!/bin/sh

# This file serves as a post-commit example.
# It should be stored in '.git./hooks/post-commit'

USER="..."                                              # Specify the user name in Jenkins
API_TOKEN="..."                                         # Specify the user API token in Jenkins
JOB_NAME="..."                                          # Specify the job name in Jenkins
JOB_URL="http://128.174.133.164:8080/job/${JOB_NAME}"   # Specify the job url in Jenkins

function AddBuildParameter() {
  LIST_BUILD_PARAM="${LIST_BUILD_PARAM}&$1"
}

AddBuildParameter "token=..."     # User job token in Jenkins

# # Optional build parameters
# AddBuildParameter "build_type=Debug"
# AddBuildParameter "git_branch=master"
# AddBuildParameter "compiler=intel"
# AddBuildParameter "compiler_version=18.0.0"
# AddBuildParameter "run_tests=false"

curl --user "${USER}:${API_TOKEN}" -X POST "${JOB_URL}/buildWithParameters?${LIST_BUILD_PARAM}"
